site_name: moonshine-lite
repo_url: https://github.com/elyase/moonshine-lite
site_url: https://elyase.github.io/moonshine-lite
site_description: Lite wrapper for the useful-moonshine speech to text models
site_author: Yaser Martinez Palenzuela
edit_uri: edit/main/docs/
repo_name: elyase/moonshine-lite
copyright: Maintained by <a href="https://elyase.com">elyase</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [moonshine_lite]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/elyase/moonshine-lite
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/moonshine-lite

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
